# Generated by Django 2.1.4 on 2020-03-10 15:43

from django.db import migrations, models
import grading.models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_auto_20200310_1036'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects', grading.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
