# Generated by Django 2.1.4 on 2020-03-15 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_enrollement_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='session',
        ),
        migrations.AddField(
            model_name='enrollement',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grading.Session'),
        ),
    ]
